### ISSUE TITLE
Admin Styles: RTL

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#100]
Hey, I would like to start actively pursuing this.

Some things I think are vital:
- Ability to switch between RTL/LTR in the same site painlessly depending on the i18n setting.
- Ease of maintainability

The most logical approach, it seems to me, is:
- Put an `rtl` class on `<html>`, and then do something like this in the LESS:

``` less
body{
    direction: ltr;
   .rtl &{
      direction: rtl;
   }
}

.myElement{
    margin: 10px 0 5px 15px; 
    color: blue;
    padding: 25px;

   .rtl &{
       margin: 10px 15px 5px 0; /* the difference in RTL */
    }
}
```

Any thoughts?
